#! /usr/bin/env bash
#
#   Copyright (c) 2015-2017 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
if [ "${TRACE}" = "YES" ]
then
   set -x
fi

MULLE_EXECUTABLE_VERSION_MAJOR=1
MULLE_EXECUTABLE_VERSION_MINOR=0
MULLE_EXECUTABLE_VERSION_PATCH=0

MULLE_EXECUTABLE_VERSION="${MULLE_EXECUTABLE_VERSION_MAJOR}.${MULLE_EXECUTABLE_VERSION_MINOR}.${MULLE_EXECUTABLE_VERSION_PATCH}"


MULLE_EXECUTABLE_BASHFUNCTIONS="1"


#
# This is the main user interface to mulle-fetch
# sorta like git
#

trap_fail()
{
   exit 1
}


SHOWN_COMMANDS="\
   fetch         : fetch archive or repository [default]
   update        : update repository (-> git fetch)
   upgrade       : upgrade repository (-> git pull)
   version       : print mulle-fetch version"


HIDDEN_COMMANDS="\
   git           : run git command on repository
   library-path  : print path to mulle-fetch libexec
   tag           : tag repository
   uname         : mulle-fetchs simplified uname(1)"


print_commands()
{
   local  show_all="${1:-NO}"

   echo "${SHOWN_COMMANDS}"

   if [ "${show_all}" != "NO" ]
   then
      echo "${HIDDEN_COMMANDS}"
   fi
}


usage()
{
   local  verbose="${1:-NO}"

   cat <<EOF
Usage:
   ${MULLE_EXECUTABLE_NAME} [flags] [command] [options]

   Fetches tar archive, git repositories, svn repositories and more.
   Fetch a tar archive like this:

      mulle-fetch fetch --scm tar --directory <dir> <url>

   Fetch a git archive like this:

      mulle-fetch fetch --branch release <url>

Flags:
   -f        : force operation
EOF

   options_technical_flags_usage

   cat <<EOF

Commands:
EOF

   print_commands "${verbose}" | sort


   if [ "${verbose}" = "NO" ]
   then
      cat <<EOF
      (use mulle-fetch -v help to show more commands)
EOF
   fi

   cat <<EOF
Options are command specific. Use mulle-fetch <command> -h for help.
EOF

   exit 1
}


#
# stolen from:
# http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
# ----
#
_prepend_path_if_relative()
{
   case "$2" in
      /*)
         echo "$2"
      ;;
      *)
         echo "$1/$2"
      ;;
   esac
}


resolve_symlinks()
{
   local dir_context
   local linkpath

   if linkpath="`readlink "$1"`"
   then
      dir_context=`dirname -- "$1"`
      resolve_symlinks "`_prepend_path_if_relative "${dir_context}" "${linkpath}"`"
   else
      echo "$1"
   fi
}


fetch_libexec_path()
{
   local executablepath="$1"

   local exedir
   local exedirpath
   local prefix
   local libexecpath

   case "${executablepath}" in
      \.*|/*|~*)
      ;;

      *)
         executablepath="`command -v "${executablepath}"`"
      ;;
   esac

   executablepath="`resolve_symlinks "${executablepath}"`"
   exedirpath="`dirname "${executablepath}"`"
   prefix="`dirname "${exedirpath}"`"
   libexecpath="${prefix}/libexec/mulle-fetch"

   if [ ! -x "${libexecpath}/mulle-fetch-fetch.sh" ]
   then
      libexecpath="${exedirpath}/src"
   fi

   case "$libexecpath" in
      /*|~*)
      ;;

      *)
         libexecpath="$PWD/$libexecpath"
      ;;
   esac

   if [ -x "${libexecpath}/mulle-fetch-fetch.sh" ]
   then
      echo "${libexecpath}"
   fi
}


init()
{
   #
   # minimal setup exit
   #
   if [ "$1" = "version" ]
   then
      echo "${MULLE_EXECUTABLE_VERSION}"
      exit 0
   fi

   MULLE_FETCH_LIBEXEC_DIR="`fetch_libexec_path "$0"`"
   if [ -z "${MULLE_FETCH_LIBEXEC_DIR}" ]
   then
      echo "Fatal Error: Could not find libexec for ${MULLE_EXECUTABLE} ($PWD)" >&2
      exit 1
   fi

   #
   # minimal setup exit
   #
   if [ "$1" = "library-path" ]
   then
      echo "${MULLE_FETCH_LIBEXEC_DIR}"
      exit 0
   fi

   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env library-path 2> /dev/null`"
   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
   then
      if [ -z "`command -v "${executablepath}"`" ]
      then
          echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
      else
         echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
      fi
      exit 1
   fi

   PATH="${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}:$PATH"
   PATH="${MULLE_FETCH_LIBEXEC_DIR}:$PATH"
   export PATH

   if [ ! -z "${MULLE_FETCH_LIBEXEC_TRACE}" ]
   then
      echo "PATH=$PATH" >&2
   fi

   #
   # to make these includes faster don't search via PATH
   # but have PATH as fallback
   #
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-string.sh"   &&
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-logging.sh"  &&
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-exekutor.sh" &&
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-options.sh"

   if [ $? -ne 0 ]
   then
      fail "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
   fi

   #  set -e # more pain then gain in the end
   #  set -u # doesn't work with my style

   trap trap_fail INT
   set -o pipefail
}


main()
{
   local MULLE_FLAG_ANSWER="ASK"
   local MULLE_FLAG_MAGNUM_FORCE="NONE"
   local MULLE_FLAG_IGNORE_GRAVEYARD="NO"
   local MULLE_FLAG_VERBOSE_BUILD="NO"
   local MULLE_FLAG_LENIENT="NO"

   # technical flags
   local MULLE_FLAG_DONT_DEFER="NO"
   local MULLE_FLAG_EXEKUTOR_DRY_RUN="NO"
   local MULLE_FLAG_CREATE_SYMLINKS  # default empty
   local MULLE_FLAG_FOLLOW_SYMLINKS="YES"
   local MULLE_FLAG_LOG_LOCAL="NO"
   local MULLE_FLAG_LOG_DEBUG="NO"
   local MULLE_FLAG_LOG_EXEKUTOR="NO"
   local MULLE_FLAG_LOG_FLUFF="NO"
   local MULLE_FLAG_LOG_SCRIPTS="NO"
   local MULLE_FLAG_LOG_SETTINGS="NO"
   local MULLE_FLAG_LOG_VERBOSE="NO"
   local MULLE_FLAG_LOG_MERGE="NO"
   local MULLE_TRACE_PATHS_FLIP_X="NO"
   local MULLE_TRACE_POSTPONE="NO"
   local MULLE_TRACE_RESOLVER_FLIP_X="NO"
   local MULLE_TRACE_SETTINGS_FLIP_X="NO"

   #
   # simple option handling
   #
   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -a|--prefer-origin)
            MULLE_FLAG_ANSWER="NO"
          ;;

         -y|--prefer-local)
            MULLE_FLAG_ANSWER="YES"
         ;;

         # short cut for fetch
         --symlinks)
            MULLE_FLAG_CREATE_SYMLINKS="YES"
         ;;

         # used persistently throughout so it's global
         --follow-symlinks)
            MULLE_FLAG_FOLLOW_SYMLINKS="YES"
         ;;

         -f|--force)
            MULLE_FLAG_MAGNUM_FORCE="BOTH"
         ;;

         -h|--help)
            usage "${MULLE_TRACE}"
         ;;

         --git-terminal-prompt)
            [ $# -eq 1 ] && fail "missing argument to \"$1\""
            shift

            GIT_TERMINAL_PROMPT="$1"
            export GIT_TERMINAL_PROMPT
         ;;

         --version)
            echo "${MULLE_EXECUTABLE_VERSION}"
            exit 0
         ;;

         -*)
            log_error "${MULLE_EXECUTABLE_FAIL_PREFIX}: Unknown option \"$1\""
            usage
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}"


   #
   # some commands only run when we have a .bootstrap folder
   # we do it somewhat like git, and progress up the directory
   # hierarchy until we find a .bootstrap or .bootstrap.local folder
   # this is useful for `mulle-fetch paths` (with absolute paths)
   #
   local cmd

   cmd="${1:-fetch}"

   MULLE_EXECUTABLE_FAIL_PREFIX="${MULLE_EXECUTABLE_NAME} ${cmd}"
   [ $# -eq 0 ] || shift

   MULLE_EXECUTABLE_OPTIONS="$@"

   case "${cmd}" in
      fetch)
         . mulle-fetch-fetch.sh

         DONT_ASK_AFTER_WARNING=YES fetch_main "$@" || exit 1
      ;;

      git)
         . mulle-fetch-git.sh

         git_main "$@" || exit 1
      ;;

      help)
         usage "${MULLE_TRACE}" || exit 1
      ;;

      library-path)
         echo "${MULLE_FETCH_LIBEXEC_DIR}"
         exit 0
      ;;

      tag)
         . mulle-fetch-tag.sh

         tag_main "$@" || exit 1
      ;;

      uname)
         echo "${UNAME}"
         exit 0
      ;;

      update)
         . mulle-fetch-fetch.sh

         update_main "$@" || exit 1
      ;;

      upgrade)
         . mulle-fetch-fetch.sh

         upgrade_main "$@" || exit 1
      ;;

      version)
         echo "${MULLE_EXECUTABLE_VERSION}"
         return 0
      ;;

      *)
         log_error "${MULLE_EXECUTABLE_FAIL_PREFIX}: Unknown command \"${cmd}\""
         usage
      ;;
   esac
}


#
# leading backslash ? looks like we're getting called from
# mingw via a .BAT or so
#
case "$PATH" in
   '\\'*)
      PATH="`tr '\\' '/' <<< "${PATH}"`"
   ;;
esac

#
# service both names (mulle-fetch and mulle-brew)
#
MULLE_EXECUTABLE="$0"
MULLE_EXECUTABLE_NAME="`basename -- "$0"`"

MULLE_EXECUTABLE_PATH="$0"
case "$MULLE_EXECUTABLE" in
   /*|~*)
      MULLE_EXECUTABLE_PATH="$MULLE_EXECUTABLE"
   ;;

   *)
      MULLE_EXECUTABLE_PATH="$PWD/$MULLE_EXECUTABLE"
   ;;
esac
MULLE_EXECUTABLE_FAIL_PREFIX="${MULLE_EXECUTABLE_NAME}"
MULLE_EXECUTABLE_PID="$$"
MULLE_EXECUTABLE_ENV_PATH="$PATH"
export MULLE_EXECUTABLE_PID

MULLE_ARGUMENTS="$*"

init "$@" # needs params
main "$@"

trap - TERM EXIT
