#! /bin/sh

[ "${TRACE}" = "YES" ] && set -x


TEST_DIR="`dirname "$0"`"
PROJECT_DIR="$( cd "${TEST_DIR}/.." ; pwd -P)"

PATH="${PROJECT_DIR}:$PATH"
export PATH


main()
{
   _options_mini_main "$@"

   MULLE_FETCH="`which mulle-fetch`" || exit 1

   local i

   log_verbose "mulle-fetch: `mulle-fetch version` (`mulle-fetch library-path`)"

   OUTPUT_DEVICE=
   for i in "${TEST_DIR}"/*
   do
      if [ -x "$i/run-test" ]
      then
         log_verbose "------------------------------------------"
         log_info    "$i:"
         log_verbose "------------------------------------------"
         if [ "${MULLE_FLAG_LOG_TERSE}" = "YES" ]
         then
            ( cd "$i" && ./run-test "$@" > /dev/null 2>&1 ) || fail "Test \"$i\" failed"
         else
            ( cd "$i" && ./run-test "$@" ) || fail "Test \"$i\" failed"
         fi
      fi
   done
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env library-path`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
}


init "$@"
main "$@"

