#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x


run_mulle_fetch()
{
   log_fluff "####################################"
   log_fluff ${MULLE_FETCH} ${MULLE_FETCH_FLAGS} "$@"
   log_fluff "####################################"

   exekutor ${MULLE_FETCH} ${MULLE_FETCH_FLAGS} "$@"
}


_setup_demo_repo()
{
   git init

   redirect_exekutor version echo "1.0.0"
   exekutor git add version
   exekutor git commit -m "inital version 1.0.0 (tagged)"
   exekutor git tag "1.0.0"

   redirect_exekutor version echo "2.0.0"
   exekutor git commit -m "version 2.0.0 (tagged)" version
   exekutor git tag "2.0.0"

   exekutor git checkout -b patch master

   redirect_exekutor version echo "2.0.1"
   exekutor git commit -m "version 2.0.1 (tagged)" version
   exekutor git tag "2.0.1"

   exekutor git checkout master

   redirect_exekutor version echo "3.0.0"
   exekutor git commit -m "version 3.0.0 (tagged)" version
   exekutor git tag "3.0.0"

   redirect_exekutor version echo "3.1.0"
   exekutor git commit -m "version 3.1.0 (tagged)" version
   exekutor git tag "3.1.0"
}


setup_demo_repo()
{
   (
      set -e
      mkdir_if_missing "$1" &&
      exekutor cd "$1" && _setup_demo_repo
      set +e
   )
}


expect_version()
{
   local dstdir="$1"
   local expected="$2"

   local version

   version="`exekutor cat "${dstdir}/version"`"
   if exekutor [ "${version}" != "${expected}" ]
   then
      exekutor fail "Expected to find version \"${expected}\" but got \"${version}\""
   fi
}


main()
{
   MULLE_FETCH_FLAGS="$@"

   _options_mini_main "$@" && set -x

   local directory
   local dstdir
   local repo

   r_make_tmp_directory || exit 1
   directory="${RVAL:-/tmp/exekutor}"

   repo="${directory}/repo"
   dstdir="${directory}/dstdir"

   setup_demo_repo "${repo}" || exit 1

   run_mulle_fetch fetch "${repo}" "${dstdir}" || exit 1

   run_mulle_fetch checkout -b master "${dstdir}" || exit 1

   run_mulle_fetch checkout -b master "${dstdir}" || exit 1
   expect_version "${dstdir}" "3.1.0"
   log_verbose "----- #1 PASSED -----"

   run_mulle_fetch checkout -t 3.0.0 -b master "${dstdir}" || exit 1
   expect_version "${dstdir}" "3.0.0"
   log_verbose "----- #2 PASSED -----"

   run_mulle_fetch checkout -b patch "${dstdir}" || exit 1
   expect_version "${dstdir}" "2.0.1"
   log_verbose "----- #3 PASSED -----"

   run_mulle_fetch checkout -t 2.0.0 -b patch "${dstdir}" || exit 1
   expect_version "${dstdir}" "2.0.0"
   log_verbose "----- #4 PASSED -----"

   if run_mulle_fetch checkout -t 2.0.2 -b patch "${dstdir}"
   then
      exekutor fail "unexpected success checking out unknown tag 2.0.2"
   fi
   log_verbose "----- #5 PASSED -----"

   rmdir_safer "${dstdir}"
   if run_mulle_fetch checkout -b release "${dstdir}"
   then
      exekutor fail "unexpected checking out in empty dstdir"
   fi
   log_verbose "----- #8 PASSED -----"

   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}



init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_FETCH="${MULLE_FETCH:-${PWD}/../../mulle-fetch}"
}



init "$@"
main "$@"

