#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x


run_mulle_fetch()
{
   log_fluff "####################################"
   log_fluff ${MULLE_FETCH} ${MULLE_FETCH_FLAGS} "$@"
   log_fluff "####################################"

   exekutor ${MULLE_FETCH} ${MULLE_FETCH_FLAGS} "$@"
}


_setup_demo_repo()
{
   git init

   redirect_exekutor version echo "1.0.0"
   exekutor git add version
   exekutor git commit -m "inital version 1.0.0 (tagged)"
   exekutor git tag "1.0.0"

}

_update_demo_repo()
{
   redirect_exekutor version echo "2.0.0"
   exekutor git commit -m "version 2.0.0 (tagged)" version
   exekutor git tag "2.0.0"
}


setup_demo_repo()
{
   (
      set -e
      mkdir_if_missing "$1" &&
      exekutor cd "$1" && _setup_demo_repo
      set +e
   )
}


update_demo_repo()
{
   (
      set -e
      exekutor cd "$1" && _update_demo_repo
      set +e
   )
}

expect_version()
{
   local dstdir="$1"
   local expected="$2"

   local version

   version="`exekutor cat "${dstdir}/version"`"
   if exekutor [ "${version}" != "${expected}" ]
   then
      exekutor fail "Expected to find version \"${expected}\" but got \"${version}\""
   fi
}


main()
{
   MULLE_FETCH_FLAGS="$@"

   _options_mini_main "$@"

   local repo

   local directory
   local dstdir
   local repo

   directory="`make_tmp_directory`" || exit 1
   directory="${directory:-/tmp/exekutor}"

   repo="${directory}/repo"
   dstdir="${directory}/dstdir"

   setup_demo_repo "${repo}" || exit 1

   run_mulle_fetch fetch "${repo}" "${dstdir}" || exit 1
   if run_mulle_fetch checkout -t "2.0.0" "${dstdir}"
   then
      exekutor fail "unexpected checking out 2.0.0"
   fi
   log_verbose "----- #1 PASSED -----"

   update_demo_repo "${repo:-/tmp/exekutor}" || exit 1
   expect_version "${dstdir}" "1.0.0"
   log_verbose "----- #2 PASSED -----"

   run_mulle_fetch checkout -t "2.0.0" "${dstdir}" || exit 1
   expect_version "${dstdir}" "2.0.0"
   log_verbose "----- #3 PASSED -----"

   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}



init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_FETCH="${MULLE_FETCH:-${PWD}/../../mulle-fetch}"
}



init "$@"
main "$@"

